Let $K_{ij} : = \langle x_i, x_j\rangle$
$$
\min_{\beta_1,\dots, \beta_n \in \mathbb{R}^{k-1}}  
\quad  
\frac{1}{2} 
\sum_{i,j \in [n]}K_{ij} \beta_i^\top 
\Pi_{y_i} \Theta \Pi_{y_j}^\top 
\beta_j
-
\sum_{\ell \in [n]} \mathbf{1}^\top \beta_\ell
$$

For Crammer-Singer SVM:
$$
0 \le \sum_{j \in [k-1]}\beta_{ij} \le C, \quad \forall i \in [n]
$$

For Weston-Watkins SVM:
$$
0 \le \max_{j \in [k-1]}\beta_{ij} \le C, \quad \forall i \in [n]
$$

---

We call  $ \Pi_{y_i} \Theta \Pi_{y_j}^\top $ the "label kernel".

# Computing the "label kernel"
We note that $M_{y_i,y_j} := \Pi_{y_i} \Theta \Pi_{y_j}^\top$ is a $(k-1)\times(k-1)$ matrix that depends only on $k$, $y_i$ and $y_j$. 
The matrix $M_{y_i,y_j}$ can be computed easily using the function $\mathtt{label\_kernel}(y_1,y_2)$ given in 
`02_PI_Theta_PI_T_formula.ipynb`.

We also need a way to recover the original SVM.

# Recovering the original SVM

The formula is:
$$
\mathbf{W} = - \sum_{i \in [n]} x_i \alpha_i^\top
$$
where the $\alpha_i$'s are the ordinary dual variables in $\mathbb{R}^k$.
The conversion formula is
$$
\alpha_i = 
-S_{y_i}^\top R^\top \beta_i
$$

Hence, the formula in terms of the the $\beta_i$'s is
$$\mathbf{W} = \sum_{i\in [n]} x_i \beta_i^\top R S_{y_i}$$
Using the identity $R S_{y} = \Pi_y R$ (see `03_permutation_matrice_label_code.ipynb`), we have
$$\mathbf{W} = \sum_{i\in [n]} x_i \beta_i^\top \Pi_{y_i}R$$

From [WS2021], at the beginning of Section 3:

$
\mathbf{R} = \begin{bmatrix}
-\mathbf{I}_{k-1}
&
\mathbf{1} 
\end{bmatrix}
$

In [3]:
import numpy as np
k  = 5
R = np.hstack((- np.eye(k-1),  np.ones((k-1,1)) ))
R@R.T

array([[2., 1., 1., 1.],
       [1., 2., 1., 1.],
       [1., 1., 2., 1.],
       [1., 1., 1., 2.]])

In [ ]:
def per_mat(y):
    SG = np.eye(k)
    sig = list(range(k))
    sig[y] = k-1
    sig[k-1] = y
    return SG[sig,:]
#     return SG[:, sig]

In [2]:
y1 = 1
y2 = 2
R@per_mat(y1)@per_mat(y2)@R.T

NameError: name 'R' is not defined

In [3]:
PI[y1]@(np.eye(k-1)+np.ones((k-1,k-1)))@PI[y2].T

NameError: name 'PI' is not defined

In [4]:
SG = np.eye(k)

y1 = 2
y2 = 4



NameError: name 'np' is not defined

In [47]:
import numpy as np
k = 5
PI = []
for y in range(k-1):
    PIy = np.eye(k-1)
    PIy[:,y] = -1
    PI.append(PIy)
PI.append(np.eye(k-1))
PI

[array([[-1.,  0.,  0.,  0.],
        [-1.,  1.,  0.,  0.],
        [-1.,  0.,  1.,  0.],
        [-1.,  0.,  0.,  1.]]),
 array([[ 1., -1.,  0.,  0.],
        [ 0., -1.,  0.,  0.],
        [ 0., -1.,  1.,  0.],
        [ 0., -1.,  0.,  1.]]),
 array([[ 1.,  0., -1.,  0.],
        [ 0.,  1., -1.,  0.],
        [ 0.,  0., -1.,  0.],
        [ 0.,  0., -1.,  1.]]),
 array([[ 1.,  0.,  0., -1.],
        [ 0.,  1.,  0., -1.],
        [ 0.,  0.,  1., -1.],
        [ 0.,  0.,  0., -1.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])]

In [8]:
PI[0]@PI[3].T

array([[-1.,  0.,  0.,  0.],
       [-1.,  1.,  0.,  0.],
       [-1.,  0.,  1.,  0.],
       [-2., -1., -1., -1.]])